trigger:
- dev
- master

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'
  NugetPachageCachePath: 'D:\a\1\.nuget\packages'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '/fbe17587-989e-4bd3-9e5d-9bab3ce8a196'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]est/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'
